tsinghua-auto4/ct_note

BOJ/2301/01/조해정_10430_나머지.py

230101 조해정 백준 10430 나머지 풀이

---

BOJ/2301/01/practice.py
BOJ/2301/02/조해정_4375_1.py

"1"부터 n으로 나눠떨어질 때까지 자릿수에 "1"을 추가합니다.
"1", "11", "111", ...

220102 조해정 백준 4375 1 풀이

---

BOJ/2301/02/조해정_4375_1.py

- [백준 4375번 문제](https://www.acmicpc.net/problem/4375)
- 내용: 
2와 5로 나누어 떨어지지 않는 정수 n(1 ≤ n ≤ 10000)가 주어졌을 때, 1로만 이루어진 n의 배수를 찾는 프로그램을 작성하시오.
- 풀이:
"1"로 시작하여 주어진 입력 n으로 나눠떨어질때까지 자릿수를 추가한다.
"1", "11", "111", ...

230102 조해정 백준 4375 1 풀이

---

BOJ/2301/03/이경훈_2609_최대공약수와 최소공배수.py

https://www.acmicpc.net/problem/2609

add: 230103 boj_2609 Solved

---

Codility/2301/03/조해정_Lesson1_Binary Gap.py

- [코딜리티 Binary Gap 문제](https://app.codility.com/programmers/lessons/1-iterations/binary_gap/)
- 문제 요약 :
10진수를 2진수로 변환하면 0, 1, 10, 11, 100, 101, 110, 111, 1000, ....
그 중에 1과 1사이에 있는 0들이 bianry gap
예) 100010000100의 binary gap = 000, 0000으로 각자 길이가 3, 4. 끝의 00은 1로 끝나지 않기 때문에 binary gap이 아니고, 우리는 여러 binary gap이 있을 때 제일 길이가 긴 것을 반환하려고 한다.
- 풀이 :
1. N이 5보다 작으면 무조건 gap = 0
2. 5이상의 N을 이진수로 변환하고, 나온 문자열을 "1"을 기준으로 split한다. "1" => "".
3. 반환한 리스트의 첫번째 요소는 무조건 1이기에 볼 필요가 없다.
4. 반환한 리스트의 마지막 요소는 원래 이진수가 '1'로 끝났다면 ''이고, 0으로 끝났다면 마지막 '0'의 나열은 gap에 해당되지 않아서 볼 필요가 없다.
5. 따라서 첫번째와 마지막 요소를 제외한 리스트에서 각 요소별로 '0'의 길이를 재고 그 중에 가장 큰 것을 gap에 넣어 반환한다.

230103 조해정 코딜리티 Lesson1 Binary Gap 풀이

---

BOJ/2301/03/김동현_1107_리모컨.py

220915 김동현 백준 1107 리모컨

---

Codility/2301/03/조해정_Codility_TapeEquilibrium.py
Codility/2301/03/조해정_Lesson2_CyclicRotation.py
Codility/2301/03/조해정_Lesson2_OddOccurrencesInArray.py
Codility/2301/03/조해정_Lesson3_FrogJmp.py
Codility/2301/03/조해정_Lesson3_PermMissingElem.py

- [코딜리티 Lesson2 CyclicRotation 문제](https://app.codility.com/programmers/lessons/2-arrays/cyclic_rotation/)
- [코딜리티 Lesson2 OddOccurrencesInArray 문제](https://app.codility.com/programmers/lessons/2-arrays/odd_occurrences_in_array/)
- [코딜리티 Lesson3 FrogJmp 문제](https://app.codility.com/programmers/lessons/3-time_complexity/frog_jmp/)
- [코딜리티 Lesson3 PermMissingElem 문제](https://app.codility.com/programmers/lessons/3-time_complexity/perm_missing_elem/)
- [코딜리티 Lesson3 TapeEquilibrium 문제](https://app.codility.com/programmers/lessons/3-time_complexity/tape_equilibrium/)
- 주석 참고

230103 조해정 코딜리티 Lesson2 Array, Lesson3 Time Complexity 문제들 풀이

---

Codility/2301/05/조해정_Lesson4_MissingInteger.py

- [코딜리티 Lesson4 MissingInteger 문제](https://app.codility.com/programmers/lessons/4-counting_elements/missing_integer/)
- 주석 참고

230103 조해정 코딜리티 Lesson4 MissingInteger 문제 풀이

---

Codility/2301/07/조해정_Lesson5_CountDiv.py
Codility/2301/07/조해정_Lesson5_GenomicRangeQuery.py

- [코딜리티 Lesson5 CountDiv 문제](https://app.codility.com/programmers/lessons/5-prefix_sums/count_div/)
- [코딜리티 Lesson5 GenomicRangeQuery 문제](https://app.codility.com/programmers/lessons/5-prefix_sums/genomic_range_query/)

230107 조해정 코딜리티 Lesson5 Prefix Sums 문제들 풀이

---

BOJ/2301/07/김동현_15649_N과 M (1).py
BOJ/2301/07/김동현_15650_N과 M (2).py
BOJ/2301/07/김동현_15651_N과 M (3).py
BOJ/2301/07/김동현_15652_N과 M (4).py
BOJ/2301/07/김동현_15654_N과 M (5).py
BOJ/2301/07/김동현_15655_N과 M (6).py
BOJ/2301/07/김동현_15656_N과 M (7).py
BOJ/2301/07/김동현_15657_N과 M (8).py
BOJ/2301/07/김동현_1748_수 이어 쓰기 1.py
BOJ/2301/07/김동현_6064_카잉달력.py

230107 boj_1748, boj_6064, boj_15649, boj_15650~15652, boj_15654~15657 Solved

230107 boj_1748, boj_6064, boj_15649, boj_15650~15652, boj_15654~15657 Solved

---

Codility/2301/09/조해정_Lesson5_MinAvgTwoSlice.py

- [코딜리티 Lesson5 MinAvgTwoSlice 문제](https://app.codility.com/programmers/lessons/5-prefix_sums/min_avg_two_slice/)
- 주석 참고
딴 좋은 방법 없을까? 생각나는 사람 코멘트 좀

230109 조해정 코딜리티 Lesson5 MinAvgTwoSlice 문제 풀이

---

Codility/2301/11/조해정_Lesson6_Distinct.py
Codility/2301/11/조해정_Lesson6_MaxProductOfThree.py
Codility/2301/11/조해정_Lesson6_Triangle.py

- [코딜리티 Lesson6 Distinct 문제](https://app.codility.com/programmers/lessons/6-sorting/distinct/)
- [코딜리티 Lesson6 MaxProductOfThree 문제](https://app.codility.com/programmers/lessons/6-sorting/max_product_of_three/)
- [코딜리티 Lesson6 Triangle 문제](https://app.codility.com/programmers/lessons/6-sorting/triangle/)

230103 조해정 코딜리티 Lesson6 Sorting 문제들 풀이

---

Codility/2301/11/조해정_Lesson6_NumberOfDiscIntersections.py

- [코딜리티 Lesson6 NumberOfDiscIntersections 문제](https://app.codility.com/programmers/lessons/6-sorting/number_of_disc_intersections/)

230103 조해정 코딜리티 Lesson6 NumberOfDiscIntersections 문제 풀이

---

Codility/2301/12/조해정_Lesson7_Brakets.py

- [코딜리티 Lesson7 Brackets 문제](https://app.codility.com/programmers/lessons/7-stacks_and_queues/brackets/)

230112 조해정 코딜리티 Lesson7 Brackets 문제 풀이

---

Swea/2301/12/이경훈_1961_숫자 배열 회전.py
Swea/2301/13/이경훈_1961_숫자 배열 회전.java

add: 230113 swea_1961 Solved

---

BOJ/2301/14/조해정_6603_로또.py

그냥 라이브러리 이용해서 풀음.
다음에 브루트 포스 문제들 풀 때 다른 방법으로 한 번 더 풀어볼 생각.

230114 조해정 백준 6603 로또 문제 풀이

---

Swea/2304/08/이경훈_5607_조합.java

add: 230408 swea_5607 solved

---

Swea/2304/09/이경훈_8382_방향전환.java

add: 230409 swea_8382 solved

---

Swea/2304/10/이경훈_2383_점심식사시간.java

add: 230410 swea_2383 solved

---

BOJ/2304/10/이경훈_2042_구간합구하기.java

add: 230411 boj_2042 solved

---

BOJ/2304/15/이경훈_2293_동전1.py
BOJ/2304/16/이경훈_2294_동전2.py

add: 230416 boj_2293, 2294 solved

---

Programmers/2306/03/이경훈_42861_섬 연결하기.py

[add: 230618 Programmers_42861 solved](https://github.com/tsinghua-auto4/ct_note/commit/549ac8ae1cc8fd5f494452a896d4cd27e5c52627)

add: 230618 Programmers_42861 solved

---

BOJ/2308/06/김동현_2530_인공지능 시계.py

add: 230806 boj_2530
